services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn plant_detection.wsgi:application --workers 4 --timeout 120"