# Generated by Django 5.1.7 on 2025-03-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_diseasedetection"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="prevention_steps",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diseasedetection",
            name="disease",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="backend.disease",
            ),
        ),
    ]
