# Generated by Django 5.1.7 on 2025-03-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={},
        ),
        migrations.RemoveField(
            model_name="page",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="page",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="page",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="page",
            name="action_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="action_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
