# Generated by Django 5.1.7 on 2025-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_alter_page_options_remove_page_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diseasedetection",
            name="area",
            field=models.CharField(
                choices=[
                    ("Zimbabwe", "Zimbabwe"),
                    ("South Africa", "South Africa"),
                    ("Zambia", "Zambia"),
                ],
                default="Zimbabwe",
                max_length=100,
            ),
        ),
    ]
